---
- name: update apt
  apt: update_cache=yes

- name: install system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - git
    - graphicsmagick # for gulp-imagemin
    - htop
    - python-software-properties
    - s3cmd
    - vim
    - wget
    - zsh

- name: configure timezone
  template: src=timezone.j2 dest=/etc/timezone

- name: more configure timezone
  file: src=/usr/share/zoneinfo/{{ server.timezone }} dest=/etc/localtime state=link force=yes backup=yes

- name: set default system language pack
  shell: locale-gen {{ server.locale }}

- name: sf helper
  copy: src=sf dest=/usr/local/bin mode=0755
