---
- name: update apt
  apt: update_cache=yes

- name: install pgmagick deps
  apt: pkg={{item}}
  with_items:
    - python-pgmagick
    - python-pip
    - python-dev
    - git-core
    - libjpeg-dev
    - libtiff-dev
    - libpng-dev
    - libjasper-dev
    - libwebp-dev

- name: install pgmagick
  pip: >
    name={{item}}
  with_items:
    - pycurl
    - numpy
    - thumbor

- name: ensure thumbor group exists
  group: name=thumbor state=present system=yes

- name: ensure thumbor user exists
  user: name=thumbor group=thumbor createhome=yes state=present home=/home/thumbor

- name: copy thumbor service file
  action: template src=thumbor.j2 dest=/etc/default/thumbor
  notify: restart thumbor

- name: copy thumbor config file
  action: template src=thumbor.conf.j2 dest=/etc/thumbor.conf
  notify: restart thumbor

- name: copy thumbor upstart script
  action: template src=upstart-thumbor.conf.j2 dest=/etc/init/thumbor.conf
  notify: restart thumbor

- name: copy thumbor worker upstart script
  action: template src=upstart-thumbor-worker.conf.j2 dest=/etc/init/thumbor-worker.conf
  notify: restart thumbor

- name: creates thumbor working directory
  file: path=/var/lib/thumbor state=directory owner=thumbor group=thumbor

- name: creates thumbor log directory
  file: path=/home/thumbor/logs state=directory owner=thumbor group=thumbor

- service: name=thumbor state=running enabled=yes
  ignore_errors: yes
