name: PHPSW
title: PHPSW · South West UK PHP User Group
description: PHP User Group, meets 2nd Wednesday of every month, in Bristol, UK, talking PHP and related technologies.

bitly:
  api:
    login: ~
    key: ~

bugsnag:
  api:
    key: ~

communities:
  - { name: Bristol Web Folk,         logo: bristol-web-folk.png,  url: http://bristolwebfolk.github.io }
  - { name: Bristol Drupal,           logo: drupal-bristol.png,    url: https://groups.drupal.org/bristol-and-west-uk }
  - { name: Bristol WordPress People, logo: bristol-wordpress.png, url: http://www.meetup.com/Bristol-WordPress-People }
  - { name: PHP South Coast,          logo: php-south-coast.png,   url: http://phpsouthcoast.co.uk }
  - { name: BrightonPHP,              logo: brighton-php.png,      url: http://brightonphp.org }
  - { name: edPUG,                    logo: edpug.png,             url: http://www.edpug.co.uk }
  - { name: PHP Dorset,               logo: php-dorset.png,        url: http://www.phpdorset.co.uk }
  - { name: PHP London,               logo: php-london.png,        url: http://phplondon.org }
  - { name: PHP Hampshire,            logo: php-hampshire.png,     url: http://phphants.co.uk }
  - { name: PHP Women,                logo: php-women.png,         url: http://phpwomen.org }
  - { name: PHP Cambridge,            logo: php-cambridge.png,     url: http://www.meetup.com/phpcambridge }
  - { name: Leeds PHP,                logo: leed-php.png,          url: http://leedsphp.org }
  - { name: PHP East Midlands,        logo: phpem.svg,             url: http://phpem.uk }
  - { name: PHP North East,           logo: phpne.png,             url: http://phpne.org.uk }
  - { name: PHP North West,           logo: phpnw.png,             url: http://conference.phpnw.org.uk }
  - { name: PHP West Midlands,        logo: phpwm.png,             url: http://phpwm.org.uk }
  - { name: PHP UK,                   logo: php-uk.png,            url: http://phpconference.co.uk }

email: info@phpsw.uk

github:
  url: https://github.com/phpsw/phpsw

invoice:
  payable_to: |
    1 Fake Street
    Bristol
    BS1 1AB

  account_name: PHPSW
  account_number: 12345678
  bic: ~
  iban: ~
  sort_code: 12-23-45

mandrill:
  api:
    key: ~

meetup:
  name: PHPSW
  url: http://www.meetup.com/php-sw
  urlname: php-sw
  urlshort: meetup.com/php-sw
  api:
    key: ~

organisers:
  steve:
    name: Steve Lacey
    slug: steve-lacey
    github: stevelacey
    meetup: 13915585
    twitter: stevelacey
    url: http://stevelacey.net

  kat:
    name: Kat Zien
    slug: kat-zien
    github: katzien
    meetup: 67450042
    twitter: kasiazien
    url: http://katzien.com

  lee:
    name: Lee Stone
    slug: lee-stone
    github: leesto
    meetup: 31894252
    twitter: leesto
    url: http://leestone.co.uk

  ade:
    name: Ade Slade
    slug: ade-slade
    github: adeslade
    meetup: 31030432
    twitter: adeslade
    url: http://adeslade.co.uk

sponsors:
  meetup:
    brightpearl:
      name: Brightpearl
      company: Brightpearl
      description: Brightpearl handles the scale and complexity of a growing multi-channel retail business
      contact:
        email: accounts@brightpearl.com
        meetup: 71856992
      url: https://www.brightpearl.com
      logo: /images/sponsors/brightpearl.png
      start: 2015-05-01
      end: ~

    ents24:
      name: Ents24
      company: Ents24
      description: The UK's busiest live entertainment guide, helping millions of fans discover live shows and buy tickets every year. Made in Bristol with PHP since 1999
      contact:
        name: Doug
        email: doug.fitzmaurice@ents24.com
        meetup: 47315872
      url: http://www.ents24.com
      logo: /images/sponsors/ents24.png
      start: 2014-08-01
      end: ~

    justeat:
      name: Just Eat
      company: Just Eat Holding Ltd
      description: Just Eat are expanding their technology development with the opening of a new specialist hub in Bristol
      contact:
        name: Simone
        email: simone.basso@just-eat.com
        meetup: 165774592
      url: http://tech.just-eat.com
      logo: /images/sponsors/just-eat.png
      start: 2014-08-01
      end: 2015-04-31

    meanbee:
      name: Meanbee
      company: Meanbee Ltd
      description: Meanbee are an ecommerce agency that specialises in the development and design of complex Magento Enterprise stores
      contact:
        name: Tom
        email: tom.robertshaw@meanbee.com
        meetup: 23546531
      url: https://www.meanbee.com
      logo: /images/sponsors/meanbee.png
      start: 2015-05-01
      end: ~

    redrock:
      name: Redrock Consulting
      company: Redrock Consulting
      description: Redrock Consulting—Ethical and transparent recruiters reaching out to Software Developers in the South-West
      contact:
        name: Matt
        email: matt.webley@redrockconsulting.co.uk
        meetup: 159981312
      url: http://www.redrockconsulting.co.uk
      logo: /images/sponsors/redrock.png
      start: 2014-08-01
      end: 2015-06-30

  event:
    basekit:
      name: BaseKit
      company: BaseKit
      description: Beautiful websites for small businesses. The world's fastest growing website editor
      contact:
        name: Richard
        email: richard.healy@basekit.com
        meetup: 8190757
      url: http://www.basekit.com
      logo: /images/sponsors/basekit.png
      start: ~
      end: ~

    mixradio:
      name: MixRadio
      company: MixRadio
      description: MixRadio, formerly Nokia MixRadio, is a global music streaming service, it's like having your own personal radio station!
      contact:
        name: Tom
        email: tcoupland@gmail.com
        meetup: ~
      url: http://www.mixrad.io
      logo: /images/sponsors/mixradio.png
      start: ~
      end: ~

  community:
    jetbrains:
      name: JetBrains
      company: JetBrains
      description: JetBrains, creator of PhpStorm - is a technology-leading software development firm specializing in the creation of intelligent development tools
      url: https://www.jetbrains.com
      logo: /images/sponsors/jetbrains.png
      start: ~
      end: ~

    zend:
      name: Zend
      company: Zend
      description: Zend is the leading provider of software and services for developing, deploying and scaling mobile and web apps written in PHP
      url: https://www.zend.com
      logo: /images/sponsors/zend.png
      start: ~
      end: ~

thumbor:
  server: ~
  security_key: ~

twitter:
  url: http://twitter.com/phpsw
  user: phpsw

vouchers: []

website:
  url: http://phpsw.uk
  urlshort: phpsw.uk

youtube:
  channel:
    id: UCjj5wcw49eACHL0rZwzDJCg
