name: PHPSW
title: PHPSW - South West UK PHP User Group
description: PHP User Group, meets 2nd Wednesday of every month, in Bristol, UK, talking PHP and related technologies.

organisers:
    -
        name: Ade Slade
        first_name: Ade
        email: adeslade@gmail.com
        photo: http://photos1.meetupstatic.com/photos/member/a/d/e/0/thumb_36884512.jpeg
        github: adeslade
        twitter: adeslade
        url: http://adeslade.co.uk
    -
        name: Steve Lacey
        first_name: Steve
        email: steve@stevelacey.net
        photo: http://photos2.meetupstatic.com/photos/member/6/e/3/4/thumb_155008212.jpeg
        github: stevelacey
        twitter: stevelacey
        url: http://stevelacey.net

github:
    url: https://github.com/phpsw/phpsw

meetup:
    name: PHPSW
    url: http://www.meetup.com/php-sw
    urlname: php-sw
    api:
        key: ~

twitter:
    url: http://twitter.com/phpsw
    user: phpsw
