---
- name: install nginx
  apt: pkg=nginx state=latest

- name: config default site
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx

- service: name=nginx state=running
